version: "3.8"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    container_name: "telestrations-redis"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    container_name: "telestrations-mongo"